### ISSUE TITLE
Any actual successes so far?

### ISSUE THREAD

**Issue by ground-effect** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#101]
People who have used Brando's tool to **successfully** JB their 32-bit iDevices running 9.3.5, leave a comment here. Be a hero and prove Brando isn't a shameless phony.

I keep seeing people claiming they've "fixed the IPA". Well what's the point of fixing the IPA if this entire thing doesn't fucking work?

And Brando, stop blocking criticisms aka truths. You're acting like that phat phuk Kim Jung Un.

**Comment by foundfallon** [comment]
No jailbreak.. Dozens fixed his .ipa plist.. Which he spend fucking 2 months on fixing.. Why don't you realize.. This is fake!
