### ISSUE TITLE
How can i install this app to my ipad 2

### ISSUE THREAD

**Issue by hoanghdit** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#105]
I can't install this app, it's error

**Comment by lordsba** [comment]
it is fake jailbreak

**Comment by tolikes1** [comment]
Its fake 1000% -_- wait black hat

**Comment by bananaNuns** [comment]
https://github.com/osxusr/nalu935

lets hope this one works , i found it on github , can someone that has more knowledge help??? does it have pontential ?
