### ISSUE TITLE
We're investigating the account.

### ISSUE THREAD

**Issue by tolikes1** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#106]
![image](https://cloud.githubusercontent.com/assets/26417787/23943611/b16752fc-0978-11e7-8db9-14f158fda2cf.png)
Hope to block you acc FAKER

**Comment by foundfallon** [comment]
Report @000x3RR0R, also! He might be Brando's fake account! He is being Brando's right hand and yelling he'll release a jailbreak for iOS 9.3.5.. (Source: issue #100) report him too!

I might be wrong.. Let's see

**Comment by 000x3RR0R** [comment]
@foundfallon what proof do you want im not brando you fucking dumbass i gave you my twitter and i didnt say 9.3.5 i said 5.1 you just like to spread rumours kys

**Comment by foundfallon** [comment]
iOS 5.1? Are you Mad? You alright?

Here's your quote: "ios 9.3.5 its going to take time but ive been working on it for a while im not going to make a eta becuase idk exactly when and its going to be REAL Fuck yalu"

You seems to have contact with Brando.. You're supporting that leech even after he fucking failed..

So, either you're his fake account trying to convince people.. Cuz any kid with brain knows that Twitter account is not their passports! Anyone can have more than one fucking Twitter account.. Stop fucking about Twitter account.. I don't believe that shit..

The truth is.. You're Brando! And fuck your ass!
