### ISSUE TITLE
It's FAKE!Dont't Ever Try

### ISSUE THREAD

**Issue by Tom201326** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#107]
That's my warning,this guy is fake,GeoSn0w has exposed it to show you the real face of him.
He's stoling the most popular ios 10 jailbreak file as we know yalu and it's like not work because nothing happend.
https://www.youtube.com/watch?v=CqxuhzCEh0Y this is the vid.
Wait for The Fried Apple team jailbreak.

DON'T EVER TRY TRUST ME.

**Comment by daokhacdoan** [comment]
Fried Apple Team’s 9.3.5 jailbreak tool that will be showcased at Black Hat Asia 2017 :)

**Comment by Tom201326** [comment]
yes i hear that they will also support 32 bit devices.

**Comment by Tom201326** [comment]
And i'm really wait for blackhat day.

**Comment by daokhacdoan** [comment]
Me too .

**Comment by Tom201326** [comment]
let's wait at 28-31 march for the day!

**Comment by daokhacdoan** [comment]
Hope support 32 bits. I need Jailbreak for my 4s Downgrade to os 7.1.2

**Comment by tolikes1** [comment]
Brando asshole! who need Brando mother facebook acc?

**Comment by Joseph54321** [comment]
with the fried apple team jailbreak support ipod 5 32 bit 9.3.5
