### ISSUE TITLE
What now ? Brando is raping us

### ISSUE THREAD

**Issue by hacks4live** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#109]
Now we know he is a fake is there hope for a downgrade or jailbreak for 32 bit ???

**Comment by macca1480** [comment]
Fried Apple Team is working on a 32 bit 9.3.5 jailbreak. Could be released by the end of the month

**Comment by colby0003** [comment]
@macca1480 not exactly 64 bit is coming first then 32 bit shortly after i saw it on there twitter but maybe im wrong we will just have to see

**Comment by lordsba** [comment]
@macca1480 I hope if you are wrong because I looking daily for 9.3.5 32 bits Lolol
my iphone 4S become boring without Cydia :D

**Comment by macca1480** [comment]
@Lordsba, know the feeling well there. I have the same

**Comment by lordsba** [comment]
@macca1480 I have iphone 4S 9.3.5 & Nintendo 3DS XL 11.3.0.36 OFW
I stressed because noway to jailbreak them nowadays Lolol

**Comment by hacks4live** [comment]
But black hat wont release 9.3.5 32 but

**Comment by macca1480** [comment]
I hope someone does release it for us, My only hope is the fried apple team at this stage

**Comment by hacks4live** [comment]
But black hat wont release 9.3.5 32 but

**Comment by macca1480** [comment]
@hacks4live, Whats the "but" for? Do you know something that we dont lol
