### ISSUE TITLE
He is gone! Pushed into his rabbithole!

### ISSUE THREAD

**Issue by detectingdragon** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#115]
Fake after all!

**Comment by ThiezModz** [comment]
yes i know man he only wants donations

**Comment by shonc502** [comment]
I called fake from the jump. Then when Geosn0w broke it down it was official!  Once the source code was released it showed it was only Yalu. A good fake to the rookie jailbreaker. But anyone that can read code can see it. Put side by side it is 100% the same as Yalu. Lmao😂😂🤣. Busted!

**Comment by bananaNuns** [comment]
https://github.com/osxusr/nalu935

lets hope this one works , i found it on github , can someone that has more knowledge help??? does it have pontential ?
