### ISSUE TITLE
Had sex with Brando last night...

### ISSUE THREAD

**Issue by ground-effect** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#118]
He was really good at being a bottom. The head he gave me was awesome. I look forward to fucking him again.

**Comment by ground-effect** [comment]
People who donated to this lil fucker, fight for your rights. I sincerely wish you guys best of luck.

**Comment by tolikes1** [comment]
report https://github.com/Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak/issues/104

**Comment by bananaNuns** [comment]
https://github.com/osxusr/nalu935

lets hope this one works , i found it on github
