### ISSUE TITLE
Guys please shut your mounth untill he release his work so i still hope to jailbreak install open ssh for downgrade only

### ISSUE THREAD

**Issue by pozzdonnz79** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#119]
All i need is open ssh for downgrade who know how to downgrade ipad3rd gen 32bit model A1430'i have saved shsh blob 5.1.1/6.0/6.1.2-3/7.1.2/9.3.2/9.3.5 so i cant downgrade using redsn0w anymore has been closed so i have only window i cant use beehind with out open open shsh is possible to downgrade using shsh blob i was saved by tiny and 3u tools 9.3.2 i saved by 3utools coz tinyumbralla have not show on window screen if i can lunch tiny i will have shsh all version but shsh blob from 3utools cant be restore to 9.3.2 it promp no longer for restore that make me crazy Help

**Comment by pozzdonnz79** [comment]
I said shut your mouth that becoz i still have chance from him but if he lie i will destroy and find him send him virus i was create by my self my virus will destroy his pc system blind cant kill my virus either so pls stop blem him wait untill he release new version thank you guys

**Comment by shonc502** [comment]
Inati0n should work

**Comment by pozzdonnz79** [comment]
It work on 64 bit only bro need help I need to downgrade untethered Jb so It not work on ipad3rd gen 32bit device but thank you for help

**Comment by shonc502** [comment]
It worked on my old 4s. It's on iOS 6 now

**Comment by hacks4live** [comment]
Ahonc506 inati0n ? Ipa downlaod somewhere ?

**Comment by shonc502** [comment]
Either YouTube it or google it. It's a zip file. You need to watch the video and have to be Jailbroke to Ssh into you're device via your computer.

**Comment by hacks4live** [comment]
Wel thanks but im on 9.3.5 and home depot orntrident are not comptiable with that ios

**Comment by Tom201326** [comment]
lol that guy think that brando is real but he's fake #107

**Comment by pozzdonnz79** [comment]
Anyway he is my last chance so don't give a fuck to him he might help for Jb coz no one do ios9.3.5 that why Remember he is my last chance so thank you

**Comment by Tom201326** [comment]
pozzdonnz79 wait for TheFriedApple team jailbreak.He lacks amount of jailbreak skill and copied stuff from luca's jailbreak so just leave it and wait to fried apple team release the jailbreak.

**Comment by bananaNuns** [comment]
https://github.com/osxusr/nalu935

lets hope this one works , i found it on github

**Comment by pozzdonnz79** [comment]
Oh man let's me try out thank you

เมื่อ 10 เม.ย. 2017 23:05 "bananaNuns" <notifications@github.com> เขียนว่า

**Comment by pozzdonnz79** [comment]
did you have an ipa ? i cant find.ipa he closed thanks

2017-04-14 22:05 GMT-07:00 Pinote High <pozzdonnz@gmail.com>:
