### ISSUE TITLE
He probably left because of all the whiners here.

### ISSUE THREAD

**Issue by al2tair** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#122]
Good job, idiots. You made him leave.

**Comment by ground-effect** [comment]
How retarded do you have to be to believe this shit is real?
People have already looked at the codes inside. It's identical to the yalu jb for 10.2. He basically stole the code from the JB for another version of iOS and claimed it to be working on 32-bit 9.3.5 devices. This entire thing is fake, idiot. Him threatening to leave was just an excuse to back off from this failed scam before shit gets out of control, you naive little kid.

**Comment by shonc502** [comment]
Man! You said that exactly as I would've. Dude used Fake code and was asshole for lying. I said from the jump it's bullshit and they all wanted to crucify me on here. Lol. Don't believe everything you hear. Especially in the realm of jailbreaking! Did you know the word "gullible" isn't in the dictionary???😂😉. Damn. Quit believing all these nobody Ass fake jailbreakers
