### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by TastyUdders** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#127]
I'm confused on if this is still being worked on or not as the last edit was 4 months ago.

**Comment by prasunk98** [comment]
I don't think so that it is still on work because jailbreaking communities don't care for 32 bit devices. That sucks. I have latest ios devices. But, i love the way ios 6 used to work on iphone 4s. Especially the performance.

**Comment by shp0ng13** [comment]
THIS PROJECT IS FAKE

**Comment by Jaspenton** [comment]
well this project isnt being continued but there is a Jailbreak for 32 bit devices. its at   [https://phoenixpwn.com/](https://phoenixpwn.com/ )
