### ISSUE TITLE
probably when is full jailbreak is going to be released?

### ISSUE THREAD

**Issue by laxmanbhusal22** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#14]
it does nothing for now...

**Comment by lewgrzegorz** [comment]
Patience grasshopper, patience.

**Comment by lewgrzegorz** [comment]
:)

**Comment by skip982** [comment]
https://www.blackhat.com/asia-17/briefings/schedule/#fried-apples-how-to-make-a-jailbreak-5457

**Comment by skip982** [comment]
We shall see.

**Comment by laxmanbhusal22** [comment]
I'm really restless for this

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
