### ISSUE TITLE
iPad 2 in landscape mode

### ISSUE THREAD

**Issue by iPadrick** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#15]
if you put the iPad 2 into landscape mode the UI is a little bit weird

**Comment by laxmanbhusal22** [comment]
yeah jailbreak by BHEFM5 is not shown

**Comment by bananaNuns** [comment]
here is a screenshot of how the ui looks on the ipad 2 (mine is ipad2.1) on landscape
![img_4922](https://cloud.githubusercontent.com/assets/25860984/23095658/0bf2a9ae-f616-11e6-8bb3-8a823a0bf164.PNG)

**Comment by Brando1235703** [comment]
Thank you for the feedback, I am aware of this issue and plan not to add landscape support.
