### ISSUE TITLE
Release Jailbreak?

### ISSUE THREAD

**Issue by Sweetboy93** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#16]
I think it's the right time to release the jailbreak with this UI interface, I say this because to us more 'than the interface that you can always upgrade affects the jailbreak, especially speed devices like the 4s we want to do the downgrade ..

You could do a release date?

**Comment by Sweetboy93** [comment]
https://www.reddit.com/r/jailbreak/comments/5us8kg/beta_ios_935_jailbreak_32_bit_b1/ 

Release JAILBREAK :D

**Comment by jailbreakgIO9** [comment]
I'm really happy for this! I'm waiting for a very, very long time... Thank you brando for the video, I really appreciate it.﻿ T^T'

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
