### ISSUE TITLE
Gooooo ! ♥ Notices ?

### ISSUE THREAD

**Issue by jailbreakgIO9** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#17]
I'm really happy for this! I'm waiting for a very, very long time... Thank you brando , I really appreciate it.﻿ good job♥

**Comment by Brando1235703** [comment]
No problem!

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
