### ISSUE TITLE
Can i use this to jailbreak my ios 9.3.5 ipad mini wifi 1?

### ISSUE THREAD

**Issue by XxStoryKillerxX** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#19]

**Comment by XxStoryKillerxX** [comment]
i mean does the ui work?

**Comment by elogili** [comment]
Not now

**Comment by shonc502** [comment]
It never will. Its fake

**Comment by shonc502** [comment]
If it's real I have 2 4s just laying here. I don't give a shit if it bricks em. Let me try it if you have it. You won't cuz u don't! 😂

**Comment by tolikes** [comment]
this shit is fake...
