### ISSUE TITLE
App crash in beta2

### ISSUE THREAD

**Issue by fongpeerapon** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#20]
App crash when I open JB32.

**Comment by elogili** [comment]
Same !

**Comment by Darkusbymaster** [comment]
Muy buenas la beta 2 da fallo en el >Ipad 3.1 wifi 9.3.5 32bits se cierra sola y no efetua jailbreak

**Comment by Darkusbymaster** [comment]
Same !

**Comment by majk2085** [comment]
I don't know why beta2 is crashing... UI was reportedly done in beta one.

I think that all this jailbreak sensation is fake ;)

**Comment by iPadrick** [comment]
guys,
just remember it is in a BETA it is not COMPLETE!!! Building a jailbreak is very diffecult so please trust him and wait.... He release updates on his twitter page @Brando1235703

**Comment by Brando1235703** [comment]
This has now been fixed in the latest commit
