### ISSUE TITLE
iphone4s offset?

### ISSUE THREAD

**Issue by erumia** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#26]
I was able to launch with iPhone 4s ios 9.3.5! And before I installed it with Home Depot I could go, but I do not know the offset ...
Can I tell you if I understand?

**Comment by alecsrobespierre** [comment]
No you don't. You have jailbreak in 9.3.5 with Home Depot or not? Be clear.

**Comment by erumia** [comment]
After all, Home Depot does not support ios 9.3.5 ...
I'm sorry…
By the way, we can not jailbreak because Home Depot requests offset.
