### ISSUE TITLE
Are you alive and still mild? 'Give us one That the farm is about to be finalized and linked to ipa.

### ISSUE THREAD

**Issue by jailbreakgIO9** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#27]
I accompany you at all times and spread links of your '' project '' for hackers to help in the process of jailbreak ios 9.3.5 yours. ^ω^'

**Comment by arkzy** [comment]
I can supply you with app icons if you like?

**Comment by Brando1235703** [comment]
Thank you!
