### ISSUE TITLE
Black Screen Flash (NOT DANGEROUS)

### ISSUE THREAD

**Issue by DavidMotesa** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#3]
Just Causes A Black Screen For 2-3 Seconds But That Is All. No Harm Is Done.

**Comment by Brando1235703** [comment]
Thank you for the feedback, I will be working to resolve this issue quickly!

**Comment by djkeno** [comment]
Hey Brando do you have a Twitter ACC?

**Comment by Brando1235703** [comment]
Yes I do, it's @brando1235703

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip

**Comment by jesuslg123** [comment]
@lordsba PM me and I will send you this project IPA
