### ISSUE TITLE
add ipad support，plz

### ISSUE THREAD

**Issue by ben3317** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#31]

**Comment by annhill2011** [comment]
![img_0713](https://cloud.githubusercontent.com/assets/25886346/23150362/e843c338-f7c0-11e6-8381-39171867c200.PNG)
Says it has been removed For Now.

**Comment by annhill2011** [comment]
Will be put back later.

**Comment by ben3317** [comment]
thanks
