### ISSUE TITLE
Change only Written one beta 1-2-3? O.o

### ISSUE THREAD

**Issue by Sweetboy93** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#32]
Explain what is the point to change only the written (IN YOUR BETA?)
Release 4 BETA with the jailbreak, otherwise keep it for you.

**Comment by damien221** [comment]
No also bug fixes

**Comment by faker1235703** [comment]
https://github.com/Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak/issues/36

**Comment by tolikes** [comment]
https://github.com/Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak/issues/28
