### ISSUE TITLE
Faker Alert Peoples !

### ISSUE THREAD

**Issue by AlertStopThis** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#34]
Go #%@%# .\. You shit you have some posts saying that would launch in such a month that would be serious in '' January '', there now you pick and do it, if you are really a hacker and not a child renting people who are good and busy q too Are sincere good people and enjoyment of a hope for something that seems to have died being thus throwing money away because of a dung of 9.3.5 that does not give to downgrade and also being that there are also many hackers down there, more until today I did not see throw a jailbreak finally with a good upgrade for the less q would be the people who use idevice 4s until today without other devices: ... Anyway, if you really are working on something complicated and myth to see ' ... '' Launch this soon because you will gain fame for truth and money if you really are an official ranking! It's ahhh you're on youtube as a kid, so stay on the comic ai up as spoiler for more peoples pras ... you're hoping for the '' jailbreak '' 9.3.5 - just like me. There is this also serves as a warning, do you think cheating pessaos will go out on unpunished? Hackers are watching you because I divulged this in several web sites, as well: Deep web, webcheat, among other hacking sites and that has good and bad people to do justice when something is active being so impune.faker junk! Https://www.youtube.com/user/Brando1235703/videos .\. -.-'
![tumblr_inline_nq78f6r41n1tp0di0_500](https://cloud.githubusercontent.com/assets/25937352/23181831/4741b6a8-f855-11e6-88bc-bac6ae002bb2.gif)

**Comment by tolikes** [comment]
Of course bro look this he no respond me https://github.com/Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak/issues/28

**Comment by laxmanbhusal22** [comment]
Your grammar is like 💩💩💩💩

**Comment by annhill2011** [comment]
I did not understand any of that 💩💩💩

**Comment by annhill2011** [comment]
Haha the video shows the one girl talking 💩 But she has her girl do the fighting.

**Comment by annhill2011** [comment]
Who wants to bet Brando closes this one?

**Comment by AlertStopThis** [comment]
I want this jailbreak more than you, why my idevice foe my first being the 4s and the first time I will use jailbreaking ;'c
![i want this jailbreak more than you why my idevice foe my first being the 4s and the first time i will use jailbreaking](https://cloud.githubusercontent.com/assets/25937352/23186886/7856610a-f867-11e6-9030-e62b63a1fa91.png)
![i want this jailbreak more than you why my idevice foe my first being the 4s and the first time i will use jailbreaking - 4](https://cloud.githubusercontent.com/assets/25937352/23187657/5ee67ca2-f86a-11e6-92d1-1f090e2f4c7c.png)
![i want this jailbreak more than you why my idevice foe my first being the 4s and the first time i will use jailbreaking -2](https://cloud.githubusercontent.com/assets/25937352/23187658/5ee92ed4-f86a-11e6-9ace-0a6f70928f02.png)
![i want this jailbreak more than you why my idevice foe my first being the 4s and the first time i will use jailbreaking -3](https://cloud.githubusercontent.com/assets/25937352/23187659/5ef2a888-f86a-11e6-9342-b63e151bd0c3.png)
![i want this jailbreak more than you why my idevice foe my first being the 4s and the first time i will use jailbreaking](https://cloud.githubusercontent.com/assets/25937352/23187660/5ef836ea-f86a-11e6-8699-78dd4b0e8d40.png)
![lol](https://cloud.githubusercontent.com/assets/25937352/23187661/5efab2bc-f86a-11e6-9e34-0cce3e740c21.png)
