### ISSUE TITLE
Haters

### ISSUE THREAD

**Issue by annhill2011** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#35]
Seems there is quite a bit of complaints on here. First it doesn't matter if the jailbreak is legit or not. If it is we get a jailbreak woot woot! If it's not what have you lost? Some time waiting? I don't see the haters contributing to the project and I sure don't see them making a jailbreak and giving it out for free. 

People let's give credit where credit is due and have patience. Just stop the negativity. 

Brando1235703 if you want to close this that's cool, I'm just tired of ungreatful rude comments by people who couldn't create a jailbreak if their life depended on it.

**Comment by tolikes** [comment]
It does not make sense what you are defending,I'm almost sure that you are Brando1235703, and you also created the laxmanbhusal22 account because only the most retarded can defend that....Brando1235703 you're a stupid kid and listen to me the internet is very little anonymous.

**Comment by tolikes** [comment]
Oh common look this shit https://twitter.com/brando1235703/status/834096823937675269 SERIUS?

**Comment by tolikes** [comment]
It is scam you think you are smart but no, your goal is to give a false hope for people to give you money.

**Comment by tolikes** [comment]
https://github.com/Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak/issues/28

**Comment by AlertStopThis** [comment]
#34 
![-q](https://cloud.githubusercontent.com/assets/25937352/23189128/3f520fea-f870-11e6-8410-07c12e33020f.png)

**Comment by annhill2011** [comment]
tolikes: I really don't give two shites what you think about me because you don't know me. I'm not a "kid", nor am I the one claiming to be making this jailbreak.

**Comment by annhill2011** [comment]
Also I'm not defending 💩

**Comment by annhill2011** [comment]
Yeah just checked out his YouTube channel and all I can say is wtf, I'm closing this "issue". Faith lost damnit I really wanted a 9.3.5 jailbreak 😡😡😡

**Comment by laxmanbhusal22** [comment]
😅😅😅😅😅😅😅 I'm from Nepal and you fucking people are like 😆😆😆😆😆😆
🖕🏼🖕🏼🖕🏼🖕🏼🖕🏼🖕🏼

**Comment by nigensalvatore** [comment]
hahaha sai ho😂😂😂 laxmanbhusal22

**Comment by laxmanbhusal22** [comment]
Haha kasta kasta kaha goey musa ka chaura darbAr haha
