### ISSUE TITLE
FAKE - I have check the codes - NOT REAL !!!

### ISSUE THREAD

**Issue by faker1235703** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#36]
NOT HOPE FOR THIS JB ! 

![1](https://cloud.githubusercontent.com/assets/25949963/23203599/7cdc8700-f8e3-11e6-87de-332cccbc2101.png)
![2](https://cloud.githubusercontent.com/assets/25949963/23203600/7cdc95d8-f8e3-11e6-9097-25309f393b14.png)
![3](https://cloud.githubusercontent.com/assets/25949963/23203601/7cdcee84-f8e3-11e6-8c8c-2daf9a6612f1.png)
![4](https://cloud.githubusercontent.com/assets/25949963/23203602/7cdd4a64-f8e3-11e6-9362-639f0f3876a7.png)

**Comment by faker1235703** [comment]
THIS is the real Person for JB!
WAIT OUT !
https://twitter.com/FriedAppleTeam

**Comment by faker1235703** [comment]
https://twitter.com/getorix

**Comment by faker1235703** [comment]
One year AGO

![5](https://cloud.githubusercontent.com/assets/25949963/23203754/31a471c0-f8e4-11e6-838e-c757b3c5365e.png)

**Comment by damien221** [comment]
No fuck u

**Comment by damien221** [comment]
No  ure fake why ? Because its beta you fucking idiot ! You troll . You're a scammer

**Comment by damien221** [comment]
I'm suck of friedappleteam they haven't posted since 19 January and check the real codes you eshol  check the /bin of the info.plist file

**Comment by nigensalvatore** [comment]
hahahah

**Comment by tolikes** [comment]
Fuck you Brandon you faker

**Comment by tolikes** [comment]
https://github.com/Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak/issues/28

**Comment by geoxhon** [comment]
Just stop https://youtu.be/JHpHMQfbr5E
