### ISSUE TITLE
losing hope :(

### ISSUE THREAD

**Issue by arkzy** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#38]
if this guy isn't legit, which a lot of people are saying, then I think that there is no hope for a 9.3.5 jailbreak :-1:

**Comment by tolikes** [comment]
Bro https://github.com/Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak/issues/28

**Comment by geoxhon** [comment]
https://youtu.be/JHpHMQfbr5E
