### ISSUE TITLE
Cydia impactor

### ISSUE THREAD

**Issue by ik595859** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#41]
Showing error when using cydia impactor on iphone 4s  
So what to do?

**Comment by alecsrobespierre** [comment]
Nothing, this thing is fake. Jailbreak does not exist for 9.3.5.

**Comment by Brando1235703** [comment]
What error are you currently getting?

**Comment by heeemo** [comment]
ineed ituns??

**Comment by Brando1235703** [comment]
No, Cydia Impactor will be needed

**Comment by ik595859** [comment]
![img_2505](https://cloud.githubusercontent.com/assets/17020614/23452724/5b0aa136-fe8b-11e6-9f44-cff37541f9dd.JPG)
this problem showing
