### ISSUE TITLE
About 7 day sign

### ISSUE THREAD

**Issue by Skellytone** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#45]
If the 7 day sign expires i lose my jb and tweaks or they just become unavaible until i redo the signage thingy?

**Comment by skip982** [comment]
They should just become unavailable until you re-sign and re-jailbreak.

**Comment by iesposta** [comment]
If you just Respring, Sleep, and don't Shut Down or use all the battery, your iDevice will stay Jailbroken. At least that's how Yalu 10.2 works on my no longer active iPhone 6. 
So unless it crashes, hard boots, or you shut down, everything will work.

Only after a crash, hard reboot or shutdown, the Yalu app will not launch, thus won't Jailbreak. 

Then you just USB the Device on to the computer, launch Impactor, drag the Yalu.ipa onto the Impactor window, enter name and password or 2nd password if you use 2
Layer password, and 20 seconds it's done. 
On your Device, Preferences, Certificates will let you accept Yalu.ipa, which you then launch and Jailbreak.

**Comment by Skellytone** [comment]
Thank you so much guys!
