### ISSUE TITLE
ipad 2.1 is only displayed at the top left

### ISSUE THREAD

**Issue by papulov** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#5]
Hello, on ipad 2.1 is only displayed at the top left, not the entire screen

**Comment by Brando1235703** [comment]
Thank you for the feedback! I am aware of the issue and currently working on fixing this issue.

**Comment by papulov** [comment]
the problem is solved now displayed in full screen mode, you can close this question.
We are waiting for the first release of the product! :)

**Comment by Brando1235703** [comment]
Yes, that's what my latest commit contains, iPad temporary support. I will close it now as you requested and not an issue anymore.
