### ISSUE TITLE
About tomorrow's release

### ISSUE THREAD

**Issue by erumia** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#51]
As for this release, is it possible to not only install Cydia impacter but also to distribute via OTA in Safari? Although it may be unreasonable ...

**Comment by muh4mm3dia** [comment]
May not release..

**Comment by lordsba** [comment]
# **as I think this rerelease will brick your iphone Lolol**

**Comment by Brando1235703** [comment]
When I publish the ipa, you will have to sign it with cydia impactor

**Comment by lordsba** [comment]
### I hope your realase will help my iphone, all I want is to Downgrade :(

**Comment by skip982** [comment]
I don't know. Prove yourself tomorrow.

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
