### ISSUE TITLE
Isn't is suppose to be out today

### ISSUE THREAD

**Issue by Jaspenton** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#54]
Isn't is suppose to be out today, i'm in New Zealand and the time is 1:22pm 9/03/2017

**Comment by MusicDistrict** [comment]
just have to give it a little more time ....

**Comment by Jaspenton** [comment]
Ok I'll wait a few more hours

**Comment by lordsba** [comment]
I'm in Algeria and time is 02:31 AM 9/3/2017 and release still not updated XD Lolol

**Comment by Brando1235703** [comment]
No, It's going to be released tomorrow, like stated on twitter, from my tweets from last night

**Comment by lordsba** [comment]
Brando1235703 you live in USA, because of that we have to wait until tomorrow ;)

**Comment by Brando1235703** [comment]
lordsba , I am from Toronto, Canada. Beta 4 release is happening tomorrow at 10 pm at night at my time

**Comment by lordsba** [comment]
so we have to wait more 26 hours from now to Christmas party, I'm going to Fully my iphone 4S 32 GO by payed applications and games from Cydia, thank you :P

**Comment by Jaspenton** [comment]
oh ok, that makes sense now

**Comment by skip982** [comment]
We shall see.

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
BY THE WAY, #50 #53 #42 #36

**Comment by DylbinHax** [comment]
Don't get too exited this can easly be fake

**Comment by adi2k17** [comment]
THIS IS FAKE.

**Comment by adi2k17** [comment]
SCAMMING!!!!!!!!!!!!!!!!!!!!!

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
