### ISSUE TITLE
Simple constraints for universal storyboard compatibility 

### ISSUE THREAD

**Issue by jezza23** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#55]
For the storyboard, you could just add constraints so that it would fit all devices

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
