### ISSUE TITLE
This is probs not a fake jelbrek

### ISSUE THREAD

**Issue by jakeHq** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#56]
#50 could be a lie kek
fried mice

**Comment by jakeHq** [comment]
and idfk why i made this lmao

**Comment by lordsba** [comment]
### we are waiting and by 10  MP Toronto time we will see the truth lol

**Comment by jakeHq** [comment]
It's fake.

**Comment by Antoankiriake** [comment]
Shitttt

**Comment by Antoankiriake** [comment]
Fake Brando

**Comment by poisonhacks0202** [comment]
fake asshole

**Comment by jakeHq** [comment]
Still could be real, I read the PM as AM so, It's not even supossed to be out!

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip

**Comment by 000x3RR0R** [comment]
@jakeHq @lordsba @Antoankiriake @poisonhacks0202 https://goo.gl/5VysMa
