### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CSammo** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#59]
How will we get the beta and when will you let us know when it is out

**Comment by Jaspenton** [comment]
It comes out at 10pm Toronto, Canada times, and we should be able to download through github.

!!!!! 6 HOURS TO GO !!!!!

**Comment by Jaspenton** [comment]
!!!! 4 HOURS TO GO !!!!!

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
