### ISSUE TITLE
Waiting

### ISSUE THREAD

**Issue by CSammo** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#63]
When is it coming out what time

**Comment by laxmanbhusal22** [comment]
Delayed for 1hour

**Comment by CSammo** [comment]
Why

**Comment by laxmanbhusal22** [comment]
He tweeted he had to Attend school program

**Comment by skip982** [comment]
Report him for fraud. That's all you can do now.

**Comment by Brando1235703** [comment]
UPDATE: I had a school event that I had to attend to since I am part of my High school's Stage Crew, beta 4 that will only support iPad 2 will be out shortly

**Comment by personifigiaovsiin** [comment]
IPAD 2...

**Comment by dennes544** [comment]
@Brando1235703 "out shortly" please tell us time range PLZ

**Comment by jezza23** [comment]
Well it's 11pm

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
