### ISSUE TITLE
When is it coming out

### ISSUE THREAD

**Issue by Joseph54321** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#65]
Its past 11, when is the jailbreak coming out.

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
its not; its fake

**Comment by jezza23** [comment]
Ain't this just wonderful

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
