### ISSUE TITLE
Can't find .app/info.plist

### ISSUE THREAD

**Issue by laxmanbhusal22** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#67]
What the         
Is this fake

**Comment by pabl0cesar** [comment]
He just copied Yalu...

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
this guy can go fuck himself

**Comment by papulov** [comment]
---------------------------
Error
---------------------------
ipa.cpp:122
cannot find .app/Info.plist
---------------------------
ОК   
---------------------------

**Comment by jezza23** [comment]
![image](https://cloud.githubusercontent.com/assets/13958660/23782717/70dc62c0-0524-11e7-8a99-9a85dadc99d9.png)
this "jb" is just a popup, r.i.p. hype

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
