### ISSUE TITLE
When is the ipod touch 5 gen coming out

### ISSUE THREAD

**Issue by Joseph54321** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#68]
Im waiting for it, currently using a 5th gen ipod, when will it come out

**Comment by jezza23** [comment]
this is a fake jb

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
