### ISSUE TITLE
If says cannot find app.info list. Help. 

### ISSUE THREAD

**Issue by Joseph54321** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#69]
I tried using this and it says app.info list. Help

**Comment by jezza23** [comment]
![image](https://cloud.githubusercontent.com/assets/13958660/23782585/7faf5cae-0523-11e7-9183-0c56a9f8414e.png)
it doesn't do anything anyways

**Comment by jezza23** [comment]
just a popup

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
