### ISSUE TITLE
a PSA to everyone

### ISSUE THREAD

**Issue by jezza23** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#70]
This is fake 
![image](https://cloud.githubusercontent.com/assets/13958660/23782787/fd7bddaa-0524-11e7-9976-a64f8044079d.png)
this image highlights what happens when you click the button, nothing... just a popup

**Comment by lordsba** [comment]
but the application don't install at all using impactor lol

Error
ipa.cpp:122
cannot find .app/Info.plist
ОК

**Comment by TheLukeGuy** [comment]
Did you decompile the IPA or something within the source code itself?

**Comment by lordsba** [comment]
did someone can download and release this project? because his owner are sick Lolol
baoyingfu.loan.raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip

**Comment by jezza23** [comment]
I decompiled to binary inside the ipa

**Comment by phm3** [comment]
In offsets.c there is a code block:
    
    void init_iphone4S_9_3_5_13G36() {
    printf("setting offsets for iPhone 4S 9.3.5\n");
    allproc_offset = 0x45717C;  //iPhone 4S 9.3.4
    kernproc_offset = 0x411134; //iPhone 4S 9.3.4

I am not a kernel dev, so i have no idea if this is legit.
