### ISSUE TITLE
Error ipa.cpp:122 cannot find .app/Info.plist

### ISSUE THREAD

**Issue by lordsba** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#71]
why I try to install in my iphone 4S and I get that error?

Error
ipa.cpp:122
cannot find .app/Info.plist
ОК

**Comment by osxusr** [comment]
@lordsba rename to .zip, unload the folder from the zip, compress the folder to a .zip, rename to .ipa, side load with impactor

**Comment by papulov** [comment]
---------------------------
Error
---------------------------
zip.cpp:558
cannot unzip `C:\Users\7777\Desktop\329.3.5Jailbreak1.ipa`
Not a zip archive
---------------------------
ОК   
---------------------------

**Comment by robonxt** [comment]
I dont think its suppose to work on 4s yet. if you read the info for the .ipa file on github: "iPad 2 only support, all other devices coming soon"

**Comment by lordsba** [comment]
baoyingfu.loan.raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip

**Comment by CallMeBrado** [comment]
Whats that link for?

**Comment by CallMeBrado** [comment]
@lordsba ??????????????????

**Comment by lordsba** [comment]
I found this link by luck, I think someone else working to jailbreak 9.3.5 ios 32 bit Lolol

**Comment by lordsba** [comment]
but badly I don't have xcode 8.2.1 to test it, I'm running under 10.7.5 lion old 2008 MacBook :(

**Comment by Noaln** [comment]
@lordsba Get up a VM if you have a windows PC.. Mac OSX has been offered free since mavericks. thats what i use untill i can get a hackintosh running...

**Comment by lordsba** [comment]
I try it with VM my PC 6 GB of RAM but mainboard don't support virtualization, I'm going to commandeer an macbook air

**Comment by Noaln** [comment]
@lordsba if u wanted you could use bootcamp with your mac then run vmware on that.. and also download an already-made VM from a torrent site...

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip

**Comment by lordsba** [comment]
I try everything I even download from Torrent Macintosh 10 GB size and didn't success :(

**Comment by detoxboss** [comment]
@osxusr I have an iPad 2 and I did exactly that, (and i have done this before with other ipa files and had it work) But when i try it with this one I get the following error:

> **http-win.cpp:158
Peer certificate cannot be authenticated with given CA certificates
SSL certificate problem: self signed certificate in certificate chain**

Not entirely sure where to go from here

**Comment by colby0003** [comment]
even if you manage to fix those issues which i did you still have to wait for the actual fix for cydia impactor.

Have Fun Waiting!

**Comment by colby0003** [comment]
if you have a mac it should work if you do the fix that i figured out

**Comment by ultrablitz** [comment]
Beta4-2 has still this error
