### ISSUE TITLE
May be Legit

### ISSUE THREAD

**Issue by poisonhacks0202** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#72]
i think this is real nd is nt a scam...
just need to be patient nd have to wait for testing on ipod touch 5th gen....
release it soon if possible

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip
