### ISSUE TITLE
peer certificate problem in impactor

### ISSUE THREAD

**Issue by bananaNuns** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#74]
i got this popup on cydia impactor
"http:-win.cpp:158 error 
Peer certificate cannot be authenticated with given CA certificates
SSL certificate problem: self signed certificate in certificate chain
"

**Comment by phm3** [comment]
https://www.reddit.com/r/jailbreak/comments/5yk401/metayes_impactor_has_an_issue/

**Comment by lordsba** [comment]
did someone can download and release this project? ( jailbreak 9.3.5 32 bit ) because his owner are sick Lolol
https://raw.githubusercontent.com/Mint-Fans/linux-package/IOS/mach-portal-32-ios935.zip

**Comment by GAMRNATI0N** [comment]
@bananaNuns I heard cydia impactor is having issues on windows (if you're using it).  Use a virtual machine to run mac on windows, since mac I heard is working perfectly fine.  Let me know if this helps, because I will try this method, when the support for 4s is released...

**Comment by jesuslg123** [comment]
@GAMRNATI0N Don't try, I am on mac and does not work too, this proyect is just fake, I have decompiled the app, and nothing it does when you press the button. Don't waste your time.

**Comment by GAMRNATI0N** [comment]
@jesuslg123 For which device?

**Comment by bananaNuns** [comment]
@GAMRNATI0N  i cant run virtial machine :/ i have amd cpu and it seems like i cant run max os x with amd :(
