### ISSUE TITLE
It's March 10th, WHERE IS THE JAILBREAK??

### ISSUE THREAD

**Issue by Paulshriner1** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#77]
The jailbreak was supposed to come out on March 9. It's March 10 and it still hasn't come out! I knew it was fake don't trust this guy wait for FriedAppleTeam for their jailbreak on March 30.

**Comment by Joseph54321** [comment]
He realeased one but only for the ipad 2

**Comment by Joseph54321** [comment]
yesterday

**Comment by Joseph54321** [comment]
around 11 pm.

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
its fake

**Comment by Joseph54321** [comment]
This is fake, look at this video, it proves it. 
https://www.youtube.com/watch?v=QpOWZ4W1Wdg

**Comment by foundfallon** [comment]
This is a teenager trying to fool us out..
Check it out!! he got exposed..!!

https://www.youtube.com/watch?v=QpOWZ4W1Wdg&t=544s
