### ISSUE TITLE
Wait for cydia impactor update) PLEASE READ!

### ISSUE THREAD

**Issue by colby0003** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#78]
If you managed to fix the problem for the jailbreak which i did you still have to wait for the fix for cydia impactor. Mac users should be good to go after the fix is released

**Comment by Joseph54321** [comment]
This is fake. 
https://www.youtube.com/watch?v=QpOWZ4W1Wdg

**Comment by 000x3RR0R** [comment]
@Joseph54321 actually youre wrong GeoSnow is so quick to make fake accusations. We dont know yet so please do post fake info
