### ISSUE TITLE
I recompiled the ipa and it is working! But all it is a black screen! I swear. You can load the ipa yourself to the device. It is in a link below.

### ISSUE THREAD

**Issue by detectingdragon** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#82]
The only thing is i open it up and it is a black screen! Stupid Faker! Here is the link: i recompiled the app. It The .app file was two folders in, when it should be in 1. here is the link for the recompiled ipa: https://drive.google.com/open?id=0B-owsd4LteFTdXFtUDc2b3RCS28

**Comment by lordsba** [comment]
maybe the black screen meaning the Pwned DFU Mode

**Comment by detectingdragon** [comment]
Whats that mean. You try it. Download the ipa from the link. It is a black screen!

**Comment by Antoankiriake** [comment]
Really DFU Mode ?????!!!!😂😂
Fake Brando

**Comment by detectingdragon** [comment]
What do you mean by dfu mode. It is a "app" with a black screen.

**Comment by lordsba** [comment]
the Pwned DFU Mode allow you to downgrade to ios 6.1.3 as I though Lolol

**Comment by detectingdragon** [comment]
No, the app itself is only a black screen! Did you download it to your device?

**Comment by Maciekwulf** [comment]
On my iPad 2 it's same.

**Comment by shonc502** [comment]
Fake, fake , fake. Geosn0w just broke it down on his YouTube channel. It's a fake version of Yalu! I've been saying this for a month now. I want you to prove me wrong. His exact words are everything was copy and pasted!! Lmao. Why do u wanna do this?  Proved by a credible source. Watch it Yourself. I'll send another message with a. Link

**Comment by colby0003** [comment]
ITS NOT DFU MODE ITS A BLACK FREAKING SCREEN!!!

**Comment by colby0003** [comment]
U CANT JUST CLICK THE HOME BUTTON AND GO TO YOUR HOME SCREEN IN DFU MODE! I KNOW BECAUSE IM A DEVELOPER MYSELF!

**Comment by detectingdragon** [comment]
The app doesn't send the device into dfu mode! When opened, the whole app is just a black screen!
