### ISSUE TITLE
Error ipa.cpp:122 cannot find .app/Info.plist

### ISSUE THREAD

**Issue by rushyaa** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#83]
Error ipa.cpp:122 cannot find .app/Info.plist
i am getting this error on iphone 4s

**Comment by oliversongsyh** [comment]
I got this error on ipad2, too

**Comment by macca1480** [comment]
Im also getting this error. On iPhone 4S

**Comment by pozzdonnz79** [comment]
Im get this error too but i have fixed install 7zip open app with 7zip drag jb app in payload folder to destop then create new folder is payload drag app into payload drag payload into .ipa remove an old folder but i found new problem is cydia impactor error 158 peer bra bra so i still cant install anyway he was create wrong .ipa i think he will fix this thank you to make .ipa

**Comment by pozzdonnz79** [comment]
All i mean open others app it shold be Payload inside payload is Application name then file inside application name may developer was sleepy so that y he made someting wrong but thank you for your work anyway

**Comment by Khanhtrinh712** [comment]
I don't install it. Cannot find .app/Info.plist
help me. Pls!
