### ISSUE TITLE
info.plist

### ISSUE THREAD

**Issue by osxusr** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#90]
it surprises me how someone is trying to make a jailbreak but doesnt know how to compile .app into a .ipa

1.) get .app
2.) make "Payload" folder
3.) put .app into "Payload" folder
4.) compress the "Payload" folder into a .zip
5.) rename the .zip to "32bit935jailbreak.ipa"
6.) file works
7.) profit

why would you make a folder and put the payload folder in that folder, how does that make any sense, its so easy to do this

**Comment by CallMeBrado** [comment]
@osxusr can you help me do this.. lmao im lost

**Comment by Jaspenton** [comment]
@osxusr can u please upload a ipa for us ;D

**Comment by 000x3RR0R** [comment]
@Jaspenton want me to?

**Comment by 000x3RR0R** [comment]
one sec

**Comment by ben3317** [comment]
is that ok？

**Comment by 000x3RR0R** [comment]
@ben3317 if i fix the ipa file for u guys
