### ISSUE TITLE
Still Black Screen

### ISSUE THREAD

**Issue by HessamGh** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#91]
I've downloaded new version. After decompress and reZIP it will install.

But still the same black screen on my ipad 2

**Comment by Jaspenton** [comment]
can u plz post ipa cause im kinda confused

**Comment by HessamGh** [comment]
You should rename file from .ipa to .zip , unzip it. then inside decompressed files you'll find a folder named "Payload". Now zip it and rename the .zip file to .ipa.
That should do it.
But still it is a black screen

**Comment by 000x3RR0R** [comment]
All the problems are getting fixed if you guys let him work and give him time you get a fast and ready to use 9.3.5 jb

**Comment by Jaspenton** [comment]
Why do you need to call it payload?
