### ISSUE TITLE
Help Me... Pls!

### ISSUE THREAD

**Issue by Khanhtrinh712** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#92]
I don't install "GitHub beta 4-3 fixes all of the bugs" on my Ipad 2. Cannot find .app/Info.plist

**Comment by Darkusbymaster** [comment]
Seame

**Comment by daokhacdoan** [comment]
Bạn là người việt hả ?

**Comment by Darkusbymaster** [comment]
Is it possible that Apple is fucking the Jailbreak and that does not let release for 32 bits? The last two released versions are the same and the light is not seen at Jailbreak
No lo entiendo este gran fallo

**Comment by 000x3RR0R** [comment]
@Khanhtrinh712 @Darkusbymaster Hey guys this tweet might help your problem!https://twitter.com/brando1235703/status/841114189833871360
