### ISSUE TITLE
I DID IT! GOOD NEWS I FIXED THE INFO.PLIST FILE ERROR

### ISSUE THREAD

**Issue by NickZestia** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#93]
SO AFTER LIKE 5 MINS I FIXED THE IPA FILE AND IT NOW WORKS! IT IS ON MY IPAD MINI 1! ILL TALK TO BRANDO ABOUT IT NOW ILL DM HIM AND ILL SEE WHAT HE SAYS!

**Comment by hacks4live** [comment]
And cydia ?

**Comment by ThiezModz** [comment]
cydia works?

**Comment by 000x3RR0R** [comment]
Well cydia should work for the supported devices once I talk to Brando about what the options are of releasing the finished ipa you guys will get a fully working device!☺️

**Comment by foundfallon** [comment]
@000x3RR0R, only if he knew what he is doing.. LOL

**Comment by foundfallon** [comment]
Here is the truth!
https://github.com/Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak/issues/96#issuecomment-286182878
