### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by albyvar** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#95]
Why in jailbreak.m there is this? This is the file that Yalu for iOS 10.1-10.2 generates when the jailbreak complete. Why is it here? Also, there is nonceenabler included. Why include this on 32 bit devices?

![jailbreak](https://cloud.githubusercontent.com/assets/12894155/23848202/681ef576-07d6-11e7-8867-a426485b6e9d.PNG)

**Comment by 000x3RR0R** [comment]
Most likely a test file that was added or maybe they used it as a installation method

**Comment by hacks4live** [comment]
@000x3RROR
Do you know the final release date ?
Or beta 5 release ?
I"m a dev as well and he copyd the yalu jb and changed the offsets 9.3.4 but still hope in this guy

**Comment by 000x3RR0R** [comment]
No I don't ask devs the finale release date because I don't wanna be annoying and it's just a mystery sorta becuase if I told you to make a 9.3.5 JB for 32 bit you're not exactly going to know when you're going to be done!

Haven't discussed that about him like I said ^^

**Comment by foundfallon** [comment]
Here's the truth about him
#50 #96
