### ISSUE TITLE
Release beta 5 with Cydia on homescreen

### ISSUE THREAD

**Issue by hacks4live** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#97]
Release a working beta 5 with cydia working and  not just ui please

**Comment by hacks4live** [comment]
Anyone is sayung you"re a real jailbreaker but please release the real jb

**Comment by hacks4live** [comment]
Please release!!!

**Comment by Darkusbymaster** [comment]
Esto esta como una cabra men,os funciona alguno o solo a users de windows?????
