### ISSUE TITLE
FIXED IPA!

### ISSUE THREAD

**Issue by 000x3RR0R** [Brando1235703/32-bit-only-iOS-9.3.5-Jailbreak#99]
I FIXED THE ERROR FOR THE ".APP/INFO.PLIST" IN THE .IPA FILE!

**Link**: http://www.mediafire.com/file/6yywe3zlpqfnjtg/329.3.5Jailbreakb4-3.zip

**Comment by ilies1988** [comment]
https://goo.gl/0Z6ynv – this goo.gl shortlink has been disabled. It was found to be violating our Terms of Service. Click here and here for more information about our terms and policies respectively.

**Comment by 000x3RR0R** [comment]
@ilies1988 i updated it
